app/models/usuario.py
from app import db

class Usuario(db.Model):
  __tablename__ = "usuarios"
  id = db.Column(db.Integer, primary_key=True,)
  nome = db.Column(db.String(50))
  email = db.Column(db.String(50))
  password = db.Column(db.Text)
  
  
  def __init__(self, nome, email, password) -> None:
    self.nome = nome
    self.email = email
    self.password = password
    
  def __repr__(self) -> str:
    return f'Usuario: {self.nome}' 

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

app.config.from_object("config.ProductionConfig")
db = SQLAlchemy(app)



#Importar Vistas
from app.views.auth import auth
app.register_blueprint(auth)

from app.views.public import public
app.register_blueprint(public)

from app.views.private import private
app.register_blueprint(private)

from app.views.jogos import jogos
app.register_blueprint(jogos)

app/views/auth.py
import functools
from flask import  render_template, redirect, request,  Blueprint, flash, g, session, url_for 
from werkzeug.security import check_password_hash, generate_password_hash
from app.models.usuario import Usuario
from app import db

auth = Blueprint("auth", __name__, url_prefix="/auth")

#Cadastrar Usuario
@auth.route("/cadastrar", methods=["GET", "POST"])
def cadatrar():

    if request.method == "POST":
      nome = request.form.get("nome")
      email = request.form.get("email")
      password = request.form.get("password")
      
      usuario = Usuario(nome, email, generate_password_hash(password))
      
      error = None
      if not nome:
        error = "Digite um nome!"
        db.session.close()
      elif not email:
        error = 'Digite um nome e-mail!'
        db.session.close()
      elif not password:
        error = "Digite um nome e-mail!"
        db.session.closed()
      
      try:
        e_mail = usuario.query.filter_by(email = email).first()
      except Exception:   
        return render_template("auth/cadastrar.html")
      print(f"esse e o erro  {e_mail} {error}")
      if e_mail == None:
        
        db.session.add(usuario) 
        db.session.commit() 
        return render_template("auth/login.html")
      else:
        error = f"O e-mail {email} ja esta cadastrado!" 
        db.session.close() 
      flash(error)  
      
    return render_template("auth/cadastrar.html")
  
  #Logar Usuario
@auth.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":     
      email = request.form.get("email")
      password = request.form.get("password") 
      
      error = None      
      try:        
        usuario = Usuario.query.filter_by(email = email).first()  
      except Exception:   
        return render_template("auth/login.html")  
     
      if usuario == None:
        error = "Usuário não cadastrado"    
        db.session.close   
      elif not check_password_hash(usuario.password, password):
        error = "Senha Incorreta"  
        db.session.close 
      if error is None:
        session.clear()
        session['user_id'] = usuario.id  
        db.session.close()      
        return redirect(url_for("private.home"))
        
      flash(error)  
    return render_template("auth/login.html")
  
  
@auth.before_app_request  
def load_logged_in_user():
  user_id = session.get('user_id') 
  
  if user_id is None:
    g.user = None 
  else:
    g.user = Usuario.query.get_or_404(user_id)  
 
@auth.route("/logout")    
def logout():
  session.clear()
  return redirect(url_for("public.index"))     

def login_required(view):
  @functools.wraps(view)
  def wrapped_view(**kwargs):
    if g.user is None:
      return redirect(url_for("auth.login"))
    return view(**kwargs)
  return wrapped_view

app/views/jogos.py
from flask import  render_template, redirect, request,  Blueprint, g



jogos = Blueprint("jogos", __name__, url_prefix="/jogos")

#index
@jogos.route("/ping_pong", methods=["GET"])
def ping_pong():
  
    return render_template("jogos/ping_pong.html", user = g.user)
  
@jogos.route("/movimento", methods=["GET"])
def movimento():
  
    return render_template("jogos/movimento.html")

@jogos.route("/relogio7s", methods=["GET"])
def relogio7s():
  
    return render_template("jogos/relogio7s.html")

app/views/private.py
from flask import  render_template, redirect, request,  Blueprint, g
from werkzeug.exceptions import abort
from app.models.usuario import Usuario
from app.views.auth import login_required


private = Blueprint("private", __name__, url_prefix="/private")

#Buscar um usuario
def get_user(id):
    user = Usuario.query.get_or_404(id)
    return user

#index
@private.route("/home", methods=["GET"])
@login_required
def home():
  
    return render_template("private/home.html", user = g.user)  

@private.route("/meus_cursos", methods=["GET"])
@login_required
def meus_cursos():
  
    return render_template("private/meus_cursos.html", user = g.user)  

app/views/public.py
from flask import  render_template, redirect, request,  Blueprint



public = Blueprint("public", __name__, url_prefix="/")

#index
@public.route("/", methods=["GET"])
def index():
  
    return render_template("auth/login.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="dark">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  {% block head %} {% endblock %}
</head>

<body>

  <nav class="navbar navbar-expand-lg w-100 bg-secondary">
    <div class="container-fluid">
      <p>Logo</p>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if g.user %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('private.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('private.home') }}">Cursos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('private.meus_cursos') }}">Meus Cursos</a>
          </li>
         
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Jogos
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{ url_for('jogos.ping_pong') }}">Ping-Pong</a></li>
              <li><a class="dropdown-item" href="">Movimento</a></li>
            </ul>
          </li>  
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.logout') }}">Sair</a>
          </li>        
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('auth.cadatrar') }}">Cadastre-se</a>
          </li>
          {% endif %}
        </ul>

        {% if g.user %}
        <a class="navbar-brand" href="#">{{ g.user.nome }}</a>
          <div id="clockContainer" class="clock-container">
            <div class="clock" id="clock"></div>
          </div>
      {% endif %}
      </div>
    </div>
  </nav>

  {% block conteudo %} {% endblock %}

  <footer class="page-footer bg-secondary font-small blue p-3">
    <div class="text-center">
      <p>© 2024 Copyright</p>
    </div>

  </footer>
  <script src="{{url_for('static', filename='scripts/relogio7s.js')}}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js
"></script>

</body>

</html>

app/templates/game.html
<head>
  <title>Plataforma de Cursos de Programação</title>
  <link rel="stylesheet" href="{{url_for("static", filename="css/game.css")}}">
</head>
{% extends 'base.html' %}

{% block conteudo %}  
<h1>Jogo do Movimento</h1>
    <div class="container">
        <div class="side-panel">
            <div class="color-container">
                <p><strong>Cores disponíveis:</strong></p>
                <div class="color-item"><div class="color-box" style="background-color: #000000;"></div> Preto (#000000)</div>
                <div class="color-item"><div class="color-box" style="background-color: #FFFFFF;"></div> Branco (#FFFFFF)</div>
                <div class="color-item"><div class="color-box" style="background-color: #FF0000;"></div> Vermelho (#FF0000)</div>
                <div class="color-item"><div class="color-box" style="background-color: #00FF00;"></div> Verde (#00FF00)</div>
                <div class="color-item"><div class="color-box" style="background-color: #0000FF;"></div> Azul (#0000FF)</div>
                <div class="color-item"><div class="color-box" style="background-color: #FFFF00;"></div> Amarelo (#FFFF00)</div>
                <div class="color-item"><div class="color-box" style="background-color: #FFA500;"></div> Laranja (#FFA500)</div>
                <div class="color-item"><div class="color-box" style="background-color: #800080;"></div> Roxo (#800080)</div>
                <div class="color-item"><div class="color-box" style="background-color: #00FFFF;"></div> Ciano (#00FFFF)</div>
                <div class="color-item"><div class="color-box" style="background-color: #FFC0CB;"></div> Rosa (#FFC0CB)</div>
                <div class="color-item"><div class="color-box" style="background-color: #A52A2A;"></div> Marrom (#A52A2A)</div>
                <div class="color-item"><div class="color-box" style="background-color: #808080;"></div> Cinza (#808080)</div>
                <div class="color-item"><div class="color-box" style="background-color: #008000;"></div> Verde Escuro (#008000)</div>
                <div class="color-item"><div class="color-box" style="background-color: #800000;"></div> Vermelho Escuro (#800000)</div>
                <div class="color-item"><div class="color-box" style="background-color: #808000;"></div> Oliva (#808000)</div>
                <div class="color-item"><div class="color-box" style="background-color: #ADD8E6;"></div> Azul Claro (#ADD8E6)</div>
                <div class="color-item"><div class="color-box" style="background-color: #F08080;"></div> Coral Claro (#F08080)</div>
                <div class="color-item"><div class="color-box" style="background-color: #FFD700;"></div> Dourado (#FFD700)</div>
                <div class="color-item"><div class="color-box" style="background-color: #DAA520;"></div> Dourado Escuro (#DAA520)</div>
                <div class="color-item"><div class="color-box" style="background-color: #4B0082;"></div> Índigo (#4B0082)</div>
            </div>
        </div>
        <canvas id="canvas" width="800" height="600"></canvas>
        <div class="side-panel">
            <div id="action-log" class="log-box"></div>
            <div id="code-log" class="log-box"></div>
        </div>
    </div>
    <input type="text" id="command" placeholder="Digite o comando">
    <button onclick="executeCommand()">Executar</button>

    <script src="{{url_for("static", filename="scripts/game.js")}}"></script>

    {% endblock %}

app/templates/index.html
<head>
  <title>Plataforma de Cursos de Programação</title>
  <link rel="stylesheet" href="{{url_for("static", filename="css/index.css")}}">
</head>
{% extends 'base.html' %}

{% block conteudo %}  
  <main>
      <section id="relogio">
          <h2>Relógio Binário</h2>
          <div id="clock-binario"></div>
          <h2>Relógio Digital</h2>
          <div class="clock-container">
              <div id="clock-digital"></div>
          </div>
          <h3>Explicação</h3>
          <p>O relógio binário mostra a hora em formato binário, onde cada dígito é representado por uma sequência de 0s e 1s. Por exemplo, se a hora é 10:15:30, em binário seria:</p>
          <p><strong>Horas:</strong> 10 em binário é 1010 <strong>Minutos:</strong> 15 em binário é 1111 <strong>Segundos:</strong> 30 em binário é 11110</p>
      </section>
  </main>
    <script src="{{url_for("static", filename="scripts/index.js")}}"></script>
{% endblock %}

app/templates/jogos/movimento.html
{% extends 'base.html' %} 
{% block head %}   
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/movimento.css') }}">

<title>Movimento</title>
{% endblock %}

{% block conteudo %}
  <h1>Jogo do Movimento</h1>
  <div class="container">
      <div class="side-panel">
          <div class="color-container">
              <p><strong>Cores disponíveis:</strong></p>
              <div class="color-item"><div class="color-box" style="background-color: #000000;"></div> Preto (#000000)</div>
              <div class="color-item"><div class="color-box" style="background-color: #FFFFFF;"></div> Branco (#FFFFFF)</div>
              <div class="color-item"><div class="color-box" style="background-color: #FF0000;"></div> Vermelho (#FF0000)</div>
              <div class="color-item"><div class="color-box" style="background-color: #00FF00;"></div> Verde (#00FF00)</div>
              <div class="color-item"><div class="color-box" style="background-color: #0000FF;"></div> Azul (#0000FF)</div>
              <div class="color-item"><div class="color-box" style="background-color: #FFFF00;"></div> Amarelo (#FFFF00)</div>
              <div class="color-item"><div class="color-box" style="background-color: #FFA500;"></div> Laranja (#FFA500)</div>
              <div class="color-item"><div class="color-box" style="background-color: #800080;"></div> Roxo (#800080)</div>
              <div class="color-item"><div class="color-box" style="background-color: #00FFFF;"></div> Ciano (#00FFFF)</div>
              <div class="color-item"><div class="color-box" style="background-color: #FFC0CB;"></div> Rosa (#FFC0CB)</div>
              <div class="color-item"><div class="color-box" style="background-color: #A52A2A;"></div> Marrom (#A52A2A)</div>
              <div class="color-item"><div class="color-box" style="background-color: #808080;"></div> Cinza (#808080)</div>
              <div class="color-item"><div class="color-box" style="background-color: #008000;"></div> Verde Escuro (#008000)</div>
              <div class="color-item"><div class="color-box" style="background-color: #800000;"></div> Vermelho Escuro (#800000)</div>
              <div class="color-item"><div class="color-box" style="background-color: #808000;"></div> Oliva (#808000)</div>
              <div class="color-item"><div class="color-box" style="background-color: #ADD8E6;"></div> Azul Claro (#ADD8E6)</div>
              <div class="color-item"><div class="color-box" style="background-color: #F08080;"></div> Coral Claro (#F08080)</div>
              <div class="color-item"><div class="color-box" style="background-color: #FFD700;"></div> Dourado (#FFD700)</div>
              <div class="color-item"><div class="color-box" style="background-color: #DAA520;"></div> Dourado Escuro (#DAA520)</div>
              <div class="color-item"><div class="color-box" style="background-color: #4B0082;"></div> Índigo (#4B0082)</div>
          </div>
      </div>
      <canvas id="canvas" width="800" height="600"></canvas>
      <div class="side-panel">
          <div id="action-log" class="log-box"></div>
          <div id="code-log" class="log-box"></div>
      </div>
  </div>
  <input type="text" id="command" placeholder="Digite o comando">
  <button onclick="executeCommand()">Executar</button>
  <script src="{{url_for('static', filename='scripts/movimento.js')}}"></script>
  {% endblock %}

app/templates/jogos/ping_pong.html
{% extends 'base.html' %}

{% block head %}   
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/ping-pong.css') }}">

<title>Ping-Pong</title>
{% endblock %}

{% block conteudo %}
<main id="main" class="game-container m-auto d-flex justify-content-center">
<div class="scoreboard">
  <div id="playerScore">{{g.user.nome}}: 0</div>
  <div id="gameTime">Tempo de jogo: 0s</div>
  <div id="opponentScore">Oponente: 0</div>
</div>
<canvas id="gameCanvas" width="800" height="400"></canvas>
</main>
<script src="{{url_for('static', filename='scripts/ping-pong.js')}}"></script>
{% endblock %}

app/templates/jogos/relogio7s.html
{% extends 'base.html' %}

{% block head %}   
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/relogio7s.css') }}">

<title>Relógio de 7 Segmentos</title>
{% endblock %}

{% block conteudo %}

<div id="clockContainer">
  <div class="clock" id="clock"></div>
</div>
<script src="{{url_for('static', filename='scripts/relogio7s.js')}}"></script>
{% endblock %}

app/templates/private/home.html
{% extends 'base.html' %}
{% block head %}
  
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">
  <title>Plataforma de Cursos de Programação</title>  
{% endblock %}

 {% block conteudo %}

<h1 class="text-center p4">Cursos Basico</h1>

<div class="row row-cols-2 row-cols-md-4 g-4 p-2">
  
  <div class="col">
    <div class="card border-success" style="max-width: 25rem; max-height: 30rem;">
      <img src="{{ url_for('static', filename='img/algoritimo.jpg') }}" class="card-img-top " alt="">
      <div class="card-body">
        <h5 class="card-title text-center">Algoritimo</h5>
        <p class="card-text ">Um curso básico de algoritmo ensina a criar uma sequência de passos lógicos para resolver problemas. Os algoritmos são usados em diversas áreas, como ciência de dados, engenharia de software, aprendizado de máquina e automação. </p>
        <div class="d-flex justify-content-end"><button type="button"  class="btn btn-primary">Inscreva-se</button></div>
        
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card border-success" style="max-width: 25rem; max-height: 30rem;">
      <img src="{{ url_for('static', filename='img/logica-progamacao.png') }}" class="card-img-top " alt="">
      <div class="card-body">
        <h5 class="card-title text-center">Logica de Progamação</h5>
        <p class="card-text ">Um curso básico de lógica de programação ensina os conceitos e regras necessários para criar códigos que possam ser interpretados e executados por dispositivos e computadores</p>
        <div class="d-flex justify-content-end"><button type="button"  class="btn btn-primary">Inscreva-se</button></div>
        
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card border-success" style="max-width: 25rem; max-height: 30rem;">
      <img src="{{ url_for('static', filename='img/linguagem-progamacao.jpeg') }}" class="card-img-top " alt="">
      <div class="card-body">
        <h5 class="card-title text-center">Linguagem de Progamação</h5>
        <p class="card-text ">A linguagem de programação é um sistema formal que permite a criação de programas informáticos através de um conjunto de regras, símbolos, palavras-chave e comandos.  </p>
        <div class="d-flex justify-content-end"><button type="button"  class="btn btn-primary">Inscreva-se</button></div>
        
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card border-success" style="max-width: 25rem; max-height: 30rem;">
      <img src="{{ url_for('static', filename='img/redes.webp') }}" class="card-img-top " alt="">
      <div class="card-body">
        <h5 class="card-title text-center">Redes</h5>
        <p class="card-text ">O curso Básico de Redes é ideal para você que tem pouca ou nenhuma experiência com Redes de Computadores começar a aprender os conceitos importantes da área como Modelo OSI, TCP/IP e Dispositivos de Redes.</p>
        <div class="d-flex justify-content-end"><button type="button"  class="btn btn-primary">Inscreva-se</button></div>
        
      </div>
    </div>
  </div>
</div>
    

{% endblock %}

app/templates/private/meus_cursos.html
{% extends 'base.html' %}

{% block head %}
  
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">
  <title>Meus Cursos</title>  
{% endblock %}

{% block conteudo %}
<h1 class="text-center p4">Meus Cursos</h1>

<div class=" justify-content-center row-cols-1 row-cols-md-1 g-1 p-2">
  
  <div class="col">
    <div class="card border-success" style="max-width: 25rem; max-height: 30rem;">
      <img src="{{ url_for('static', filename='img/algoritimo.jpg') }}" class="card-img-top " alt="">
      <div class="card-body">
        <h5 class="card-title text-center">Algoritimo</h5>
        <p class="card-text ">Um curso básico de algoritmo ensina a criar uma sequência de passos lógicos para resolver problemas. Os algoritmos são usados em diversas áreas, como ciência de dados, engenharia de software, aprendizado de máquina e automação. </p>
        <div class="d-flex justify-content-end"><button type="button"  class="btn btn-primary">iniciar</button></div>
        
      </div>
    </div>
  </div>
  
</div>
{% endblock %}